const data = {
  products: [
    {
      _id: "1",
      name: "USB mini wind power handheld Fan",
      category: "Appliance",
      image: "/images/product-1.jpg",
      price: 0.95,
      brand: "eNest",
      rating: 4.5,
      numReviews: 10,
      desc: "High quality product",
    },
    {
      _id: "2",
      name: "Robot Vacuum Cleaner Smart Remote Control",
      category: "Appliance",
      image: "/images/product-2.jpg",
      price: 148.99,
      brand: "Takdir smart store",
      rating: 4.0,
      numReviews: 15,
      desc: "Smart One-click C1. Planning type, with mop, matching tmall genie, with app mobile phone control",
    },
    {
      _id: "3",
      name: "Xiaomi New Car Vacuum Cleaner Portable Mini Handheld Vacuum Cleaner",
      category: "Appliance",
      image: "/images/product-3.jpg",
      price: 29.99,
      brand: "Xiaomi",
      rating: 4.5,
      numReviews: 50,
      desc: "Strong suction and long running time",
    },
    {
      _id: "4",
      name: "Dropshipme 2022 Essential Oils for Humidifier USB Diffuser",
      category: "Appliance",
      image: "/images/product-4.jpg",
      price: 3.49,
      brand: "Dropshipme",
      rating: 4.5,
      numReviews: 20,
      desc: "Mini USB humidifier with colorful night light for multi-purpose, decorating the car interior.",
    },
    {
      _id: "5",
      name: "OKEK Window cleaning robot vacuum cleaner window cleaner",
      category: "Appliance",
      image: "/images/product-5.jpg",
      price: 165.99,
      brand: "OKEK",
      rating: 4.5,
      numReviews: 60,
      desc: "Double disk twist wipe, Altenrnating cycle wipe clean, Smart planning",
    },
  ],
};
